spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb+srv://vallegrandeomar:oFnm1G368PeimZNj@cluster0.srr0s.mongodb.net/customerdb?retryWrites=true&w=majority&appName=Cluster0
      database: customerdb
      auto-index-creation: true
server:
  port: 8081
logging:
  level:
    root: INFO
bank:
  customer:
    collection: customers 