spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: mongodb+srv://vallegrandeomar:oFnm1G368PeimZNj@cluster0.srr0s.mongodb.net/transactiondb?retryWrites=true&w=majority&appName=Cluster0
      database: transactiondb
      auto-index-creation: true
server:
  port: 8084
logging:
  level:
    root: INFO
bank:
  transaction:
    collection: transactions 