spring:
  application:
    name: credit-service
  data:
    mongodb:
      uri: mongodb+srv://vallegrandeomar:oFnm1G368PeimZNj@cluster0.srr0s.mongodb.net/creditdb?retryWrites=true&w=majority&appName=Cluster0
      database: creditdb
      auto-index-creation: true
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8083
logging:
  level:
    root: INFO

bank:
  credit:
    collection: credits 