name: CI Microservices Java

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [customer-service, account-service, credit-service, transaction-service, config-server]
    name: Build and Test ${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          mvn -B clean install

      - name: Run tests
        run: |
          cd ${{ matrix.service }}
          mvn test

  # Ejemplo de job de despliegue (ajusta según tu entorno)
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to server
  #       run: echo "Despliegue aquí" 